version: "3"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    ports:
      - 5601:5601
    #volumes:
    #  - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - app_net

networks:
  app_net:
    external: true                 
