version: "3"
services:
  nsqlookupd:
    image: nsqio/nsq:v1.2.0
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - app_net
  nsqd:
    image: nsqio/nsq:v1.2.0
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      - app_net
  nsqadmin:
    image: nsqio/nsq:v1.2.0
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      - app_net

networks:
  app_net:
    external: true
